### ISSUE TITLE
Review and fix Hewlett Foundation grants data processing logic

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#112]
Followup to #7 / #52.

Here's what I get when I try processing Hewlett Foundation grants:

```
./scrape.py data-$today.csv
Doing year 2000, page 1/100
Downloading or decoding to JSON went wrong; trying again in a few seconds...
Traceback (most recent call last):
  File "./scrape.py", line 83, in <module>
    main()
  File "./scrape.py", line 58, in main
    j = get_query(year, page)
  File "./scrape.py", line 36, in get_query
    j = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by riceissa** [comment]
This turned out to be a [very simple fix](https://github.com/riceissa/hewlett-foundation/commit/831a3c47cc2d34cf93ba904f3c85dc6296e3e2f7) -- Hewlett had changed the query URL so I just needed to point to the new URL. Everything should work now.
